"""initial schema

Revision ID: 6ad336d0bc00
Revises: 
Create Date: 2026-04-06 16:02:04.526285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ad336d0bc00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'developer', 'viewer', name='project_role'), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index('ix_api_keys_project_id', 'api_keys', ['project_id'], unique=False)
    op.create_table('assistants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('draft', 'published', 'archived', name='assistant_state'), nullable=False),
    sa.Column('config_blob', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assistants_project_env', 'assistants', ['project_id', 'environment'], unique=False)
    op.create_index('ix_assistants_project_name_version', 'assistants', ['project_id', 'name', 'version'], unique=True)
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_call_sid', sa.String(length=64), nullable=True),
    sa.Column('parent_provider_call_sid', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='call_direction'), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=True),
    sa.Column('to_number', sa.String(length=20), nullable=True),
    sa.Column('active_assistant_id', sa.UUID(), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('initiated', 'ringing', 'in_progress', 'transferring', 'handed_off', 'completed', 'failed', 'no_answer', 'busy', 'voicemail', name='call_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('recording_status', sa.Enum('none', 'in_progress', 'paused', 'completed', 'failed', name='recording_status'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calls_project_id', 'calls', ['project_id'], unique=False)
    op.create_index('ix_calls_project_status', 'calls', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_calls_provider_call_sid'), 'calls', ['provider_call_sid'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_number_sid', sa.String(length=64), nullable=False),
    sa.Column('e164_number', sa.String(length=20), nullable=False),
    sa.Column('routing_target_type', sa.Enum('assistant', 'workflow', 'webhook', name='routing_target_type'), nullable=False),
    sa.Column('routing_target_id', sa.UUID(), nullable=True),
    sa.Column('server_url', sa.Text(), nullable=True),
    sa.Column('server_url_secret', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_number_sid')
    )
    op.create_index(op.f('ix_phone_numbers_e164_number'), 'phone_numbers', ['e164_number'], unique=False)
    op.create_index('ix_phone_numbers_project_id', 'phone_numbers', ['project_id'], unique=False)
    op.create_table('test_suites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('assistant_id', sa.UUID(), nullable=False),
    sa.Column('scenarios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_suites_project_id', 'test_suites', ['project_id'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret', sa.String(length=128), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_subs_project_id', 'webhook_subscriptions', ['project_id'], unique=False)
    op.create_table('call_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('internal_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_call_events_call_id', 'call_events', ['call_id'], unique=False)
    op.create_index('ix_call_events_call_seq', 'call_events', ['call_id', 'sequence_number'], unique=False)
    op.create_index('ix_call_events_call_type', 'call_events', ['call_id', 'event_type'], unique=False)
    op.create_table('test_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_suite_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'passed', 'failed', name='test_run_status'), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_runs_suite_id', 'test_runs', ['test_suite_id'], unique=False)
    op.create_table('tool_invocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'timed_out', name='tool_status'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tool_invocations_call_id', 'tool_invocations', ['call_id'], unique=False)
    op.create_index(op.f('ix_tool_invocations_idempotency_key'), 'tool_invocations', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_invocations_idempotency_key'), table_name='tool_invocations')
    op.drop_index('ix_tool_invocations_call_id', table_name='tool_invocations')
    op.drop_table('tool_invocations')
    op.drop_index('ix_test_runs_suite_id', table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index('ix_call_events_call_type', table_name='call_events')
    op.drop_index('ix_call_events_call_seq', table_name='call_events')
    op.drop_index('ix_call_events_call_id', table_name='call_events')
    op.drop_table('call_events')
    op.drop_index('ix_webhook_subs_project_id', table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index('ix_test_suites_project_id', table_name='test_suites')
    op.drop_table('test_suites')
    op.drop_index('ix_phone_numbers_project_id', table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_e164_number'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_calls_provider_call_sid'), table_name='calls')
    op.drop_index('ix_calls_project_status', table_name='calls')
    op.drop_index('ix_calls_project_id', table_name='calls')
    op.drop_table('calls')
    op.drop_index('ix_assistants_project_name_version', table_name='assistants')
    op.drop_index('ix_assistants_project_env', table_name='assistants')
    op.drop_table('assistants')
    op.drop_index('ix_api_keys_project_id', table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('projects')
    # ### end Alembic commands ###
